(feature) Added category block
Swetrix/marketplace-fe pull request #61
Opened 2023-03-16 00:26 UTC by Borfak

Ticket: https://github.com/Swetrix/roadmap/issues/92

2023-03-16 00:27 UTC, Blaumaus approved these changes
Good job, my friend!

2023-03-16 00:37 UTC, kruzhambus approved these changes

2023-03-16 04:11 UTC, Blaumaus requested changes

2023-03-16 04:11 UTC, Blaumaus commented on src/pages/MainPage/MainPage.jsx
>    const extensionsWithoutCategory = _filter(extensions, (extension) => !extension.category)
```suggestion
  const extensionsWithoutCategory = _filter(extensions, (extension) => !extension.category)

```

2023-03-16 04:11 UTC, Blaumaus approved these changes

2023-03-16 11:02 UTC, kruzhambus reviewed
and remove import for _isEmpty in src/utils/refreshToken.js because never used in this file

2023-03-18 14:36 UTC, kruzhambus approved these changes

2023-06-25 19:45 UTC, merged